# Change these first
owner: stefftek # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: SteffTek.de
    url: https://stefftek.de/
  - name: Discord Virgin Slayer
    url: https://dvs.stefftek.de/
  - name: Virgin Slayer V3
    url: https://virginslayer.app/
    icon: https://virginslayer.app/images/favicon.png
  - name: Virgin Slayer V3 API
    url: https://api.virginslayer.app/
    icon: https://virginslayer.app/images/favicon.png
    expectedStatusCodes:
      - 401
      - 200
  - name: Image API
    url: https://images.stefftek.de/
    icon: https://raw.githubusercontent.com/SteffTek/Status/master/assets/favicon.png
  - name: UnTubed
    url: https://untubed.de/
    icon: https://untubed.de/images/favicon.png
  - name: UnTubed API
    url: https://api.untubed.de/
    icon: https://untubed.de/images/favicon.png
    expectedStatusCodes:
      - 401
      - 200
  - name: UnTubed Webhook
    url: $UNTUBED_HOOK
    icon: https://untubed.de/images/favicon.png
    expectedStatusCodes:
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.stefftek.de
  # baseUrl: /your-repo-name
  logoUrl: "https://raw.githubusercontent.com/SteffTek/Status/master/assets/favicon.png"
  name: SteffTek Status Page
  introTitle: "Service Status Page"
  favicon: "https://raw.githubusercontent.com/SteffTek/Status/master/assets/favicon.png"
  theme: night
  navbar:
    - title: Status
      href: /
  metaTags:
    - name: "og:url"
      content: "https://status.stefftek.de/"
    - name: "og:type"
      content: "website"
    - name: "og:title"
      content: "SteffTek Status Page"
    - name: "og:description"
      content: "Service acvitity monitor and status page."
    - name: "og:image"
      content: "https://raw.githubusercontent.com/SteffTek/Status/master/assets/favicon.png"
    - name: "twitter:url"
      content: "https://status.stefftek.de/"
    - name: "twitter:domain"
      content: "status.stefftek.de"
    - name: "twitter:card"
      content: "summary"
    - name: "twitter:title"
      content: "SteffTek Status Page"
    - name: "twitter:description"
      content: "Service acvitity monitor and status page."
    - name: "twitter:image"
      content: "https://raw.githubusercontent.com/SteffTek/Status/master/assets/favicon.png"
